import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'


import Frame from './Components/Frame'
import Navigation from './Components/Navigation'
import Footer from './Components/Footer'
import Cursor_Tail from './Components/Cursor_Tail'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'SpiningRope | Blog',
  description: 'Generated by Spiningrope',
  
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  
  return (
    <html lang="en">

      <head>
    <script async
     src={`"https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=${process.env.NEXT_PUBLIC_GOOGLE_ADS_CLIENT_ID}`}
     crossOrigin="anonymous"
     />
    </head>
    
      <body className={inter.className} >

        {/* <Frame /> */}

       <Navigation />

        {children}

       <Footer />

      <Cursor_Tail />

      </body>
    </html>
  )
}
